### ISSUE TITLE
Rocket web framework description inaccurate

### ISSUE THREAD

**Issue by baarkerlounger** [nicoburns/blessed-rs#10]
The guide currently says that ["development has stalled. Avoid for new projects"](https://github.com/nicoburns/blessed-rs/blob/main/data/crates.json#L317). 

Rocket has had a new release tagged in July this year [(0.4.11)](https://github.com/SergioBenitez/Rocket/releases/tag/v0.4.11), a new release candidate for the next version bump tagged in May [(0.5)](https://github.com/SergioBenitez/Rocket/releases/tag/v0.5.0-rc.2), and has an active development channel that includes the primary developer on [Matrix](https://matrix.to/#/#rocket:mozilla.org). 

The description here doesn't seem to accurately reflect Rocket's status.

**Comment by conways-glider** [comment]
I'd disagree with this - while it has some degree of active development, it has also certainly fallen behind libraries like axum, actix, and tide. Having followed Rocket's `0.5` for a few years now, I'd certainly classify it as "stalled"

**Comment by BlackDex** [comment]
There is going to be a whole foundation being setup around Rockets framework, as is discussed a few times in matrix. Stuff like this does take time. But it certainly isn't stalled i think. It maybe is s but slowed down. But telling people to avoid it is a bit too much.

Last commit is from September. And there are other crates it uses which are also maintained by some of the main developers which are also getting patches done because of rocket.

**Comment by passcod** [comment]
Uh, I don't have a horse in any race here, but 17 days is not exactly "stalled", especially for a trivial low priority PR.

For a quick comparison, `lazy_static`'s last commit was in April, and it hasn't had a release in over 2 years, and yet it only rates an "older crate" mention in this guide.

**Comment by nicoburns** [comment]
So I'm not really willing to recommend rocket. This is because:

- I don't want to recommend the 0.4 series due to lack of async support and nightly requirement.
- I don't want to recommend the 0.5 series as it hasn't yet had a stable release, and releases have been around a year apart. This includes bugfix/security releases, which I do not consider for software exposed over a network.

Criteria for recommendation would be a regular release schedule of a the 0.5 series, and given the development history preferably also a second maintainer with release permissions.

That said, I would be willing to change the wording. Perhaps "intermittent" would be more accurate than "stalled"?
