### ISSUE TITLE
Contributing on a regular basis?

### ISSUE THREAD

**Issue by djc** [nicoburns/blessed-rs#21]
If you'd like, I'd be happy to help review changes here? You mentioned [on HN](https://news.ycombinator.com/item?id=33512766):

> I want to put together more guidance on how to contribute, and gradually transition this into more of a community maintained model over time, but I haven't had a chance to do this yet.

I could just start watching the repo -- maybe you could set up branch protection so that PRs are required, and I'd have a chance to give feedback.

**Comment by nicoburns** [comment]
@djc I'd absolutely love to have you review on changes. However, I'm somewhat reluctant to gate every change on a review step at this point, simply because the list is so incomplete and it seems to me that keeping friction to making changes and additions low should be prioritised during this initial stage. I'm not usually a "move fast and break things" kind of guy, but it seems appropriate here given that the cost of mistakenly listing a crate is quite low.

Would it be unreasonable to ask you to review the git log post-commit for the time being?

**Comment by djc** [comment]
Reviewing the git log post-commit would be annoying because I have to remember to go and look. However, if you just want to do PRs I'm fine if you merge them without waiting for my feedback, and I'll give feedback asynchronously.
