### ISSUE TITLE
Add Helix editor

### ISSUE THREAD

**Issue by digitalsanctum** [nicoburns/blessed-rs#29]

**Comment by nicoburns** [comment]
I'm not entirely sure about including Helix here. The intention of the editors section is more about how to configure the editor a user is already using for use with Rust, rather than pushing users towards new editors. I suspect that few if any readers will be using Helix (and that most of those will be more than capable of working out how to set it up for Rust by themselves).

My current plan is for VS Code to be the "blessed" recommendation for anyone who does not already have a preferred editor. Unless there is a specific benefit to using Helix over other editors for Rust code?
