### ISSUE TITLE
Add error-stack to Error handling

### ISSUE THREAD

**Issue by simonsan** [nicoburns/blessed-rs#31]
https://crates.io/crates/error-stack

Some explanatory comment on reddit:
https://www.reddit.com/r/rust/comments/vpg49v/comment/ieppvjv/?context=3

**Comment by djc** [comment]
@simonsan you seem to have a different understanding of the goal that blessed-rs aims for than I do. IMO blessed.rs is aiming to supply users with guidance on ecosystem/community guidance on widely used crates. It should not be a catalog of all the crates out there in a given problem space. As such, I don't think it makes sense to advertise this crate here.

**Comment by djc** [comment]
I mean, one reason this thing hasn't been done that much before is that "widely used" isn't that easy to define. I think recent downloads is a useful metric but definitely only one input.

**Comment by nicoburns** [comment]
> What is your metric of "widely used" then?

That's definitely a bit fuzzy. But given our existing recommendations are:

- `anyhow` with 3.6M downloads
- `thiserror` with 4.3M downloads
- `color-eyre` with 323k downloads

And `error-stack` only has `7.1k` I'd say that's quite far out of the range of being comparable.

> error-stack is the third result when sorted for relevance

I suspect that may be partly because it actually includes "error-handling" in the description, which most of the other popular error handling libraries don't. It's 16th on https://lib.rs/keywords/error, which admittedly is still relatively high. Never-the-less I think not prominent to qualify as a recommendation. It could perhaps qualify it is a "see also".

>  what is the USP then, if I could just go to crates.io and sort for most downloaded or lib.rs and take the Top3 results

The idea is actually to cut down on the amount of options you would see when doing that. Rather than having to pick between 10 different options and work out which ones are actually relevant, we present 1 or 2 options along with descriptive text to explain when each option is preferable.
